spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123456@localhost:27017/metadata?authSource=admin&authMechanism=SCRAM-SHA-256
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  endpoint: http://localhost:9000
  access-key: A76R4P1XZTSSC0MBPK8R
  secret-key: jY19VMwWBsaiOj3tz7AgyS8q601l2qMKtx4luEpb
  bucket-name: file-sharing
