services:
  mongodb:
    image: mongo:7.0
    container_name: filesharing-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: metadata
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - filesharing-network

#  minio:
#    build:
#      context: ./minio
#      dockerfile: Dockerfile
#    image: minio:latest
#    container_name: filesharing-minio
#    restart: unless-stopped
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-nam}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-nam123456}
#      THROTTLE_ENABLED: ${THROTTLE_ENABLED:-true}
#      BANDWIDTH_LIMIT: ${BANDWIDTH_LIMIT:-10mbit}
#      LATENCY_MS: ${LATENCY_MS:-50}
#      LATENCY_JITTER_MS: ${LATENCY_JITTER_MS:-10}
#      PACKET_LOSS_PERCENT: ${PACKET_LOSS_PERCENT:-0}
#      NETWORK_INTERFACE: eth0
#    cap_add:
#      - NET_ADMIN
#    volumes:
#      - minio_data:/data
#    networks:
#      - filesharing-network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: filesharing-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-nam}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-nam123456}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - filesharing-network
    healthcheck:
      test: [ "CMD", "mc",  "ready", "local" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # tạo bucket và cấu hình CORS cho minio
  minio-setup:
    image: minio/mc:latest
    container_name: filesharing-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./cors.json:/tmp/cors.json
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-nam} ${MINIO_ROOT_PASSWORD:-nam123456};
      mc mb myminio/file-sharing --ignore-existing;
      echo 'Bucket file-sharing created successfully!';
      mc anonymous set-json /tmp/cors.json myminio/file-sharing;
      echo 'CORS configuration applied successfully!';
      mc anonymous get-json myminio/file-sharing;
      exit 0;
      "
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-nam}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-nam123456}
    networks:
      - filesharing-network

  fs-mysql:
    image: mysql:8.0.43-debian
    container_name: fileSharing-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nam123
      MYSQL_DATABASE: file_sharing
      MYSQL_USER: user
      MYSQL_PASSWORD: 1210
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/sql-schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      filesharing-network:

volumes:
  mongodb_data:
  minio_data:
  mysql_data:

networks:
  filesharing-network:
    driver: bridge